---
# Handlers for RabbitMQ
- name: reset rabbitmqctl
  service: name=rabbitmqctl state=reset

- name: start_app rabbitmqctl
  service: name=rabbitmqctl state=start_app

- name: stop_app rabbitmqctl
  service: name=rabbitmqctl state=stop_app

