---
# Handlers for RabbitMQ
- name: restart rabbitmq-server
  service: name=rabbitmqctl state=reset

- name: start rabbitmq-server
  service: name=rabbitmqctl state=start_app

- name: stop rabbitmq-server
  service: name=rabbitmqctl state=stop_app

