- hosts: all
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Debug ansible facts
      debug:
        msg:
          - "OS Family: {{ ansible_os_family }}"
          - "Service Manager: {{ ansible_service_mgr }}"
          - "Package Manager: {{ ansible_pkg_mgr }}"
          - "Python Version: {{ ansible_python_version }}"
      tags: debug
    
    - name: Check if systemd is available
      command: systemctl --version
      register: systemd_check
      failed_when: false
      changed_when: false
      
    - name: Display systemd check result
      debug:
        msg: "Systemd available: {{ systemd_check.rc == 0 }}"
      tags: debug

  roles:
    - role: ansible-role-node_exporter
  vars:
    node_exporter_version: "1.6.1"
    node_exporter_binary_local_dir: ""
    node_exporter_skip_install: false
    node_exporter_web_listen_address: "0.0.0.0:9100"
    node_exporter_web_telemetry_path: "/metrics"
    node_exporter_textfile_dir: "/var/lib/node_exporter"
    node_exporter_tls_server_config: {}
    node_exporter_http_server_config: {}
    node_exporter_basic_auth_users: {}
    node_exporter_enabled_collectors:
      - systemd
    node_exporter_disabled_collectors: []
    node_exporter_binary_install_dir: "/usr/local/bin"
    node_exporter_system_group: "node-exp"
    node_exporter_system_user: "{{ node_exporter_system_group }}"
