---
- name: Deploy and Configure Metricbeat
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    # Elasticsearch Configuration
    elasticsearch_hosts:
      - "192.168.23.84:9200"
    elasticsearch_protocol: "https"
    elasticsearch_username: "elastic"
    elasticsearch_password: "Thinhphat@123"
    elasticsearch_ssl_certificate_authorities: "/etc/elasticsearch/certs/http_ca.crt"

    # Environment Settings
    environment: "production"
    datacenter: "dc1"

    # Metricbeat Package and Service
    metricbeat_package_state: "latest"
    metricbeat_service_enabled: yes
    metricbeat_service_status: "started"
    metricbeat_conf_template_enabled: true
    metricbeat_log_level: "info"

    # System Monitoring Configuration
    metricbeat_conf_system_enabled: true
    metricbeat_conf_system_metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - diskio
      - filesystem
      - fsstat
      - core
      - socket_summary

    # Docker Monitoring Configuration
    metricbeat_conf_docker_period: "10s"

    # Nginx Monitoring Configuration
    metricbeat_conf_nginx_hosts:
      - "http://127.0.0.1"
    metricbeat_conf_nginx_status_path: "nginx_status"
    metricbeat_conf_nginx_period: "10s"

    # PostgreSQL Monitoring Configuration
    metricbeat_conf_postgresql_hosts:
      - "postgres://localhost:5432"
    metricbeat_conf_postgresql_period: "10s"

    # Logging Configuration
    metricbeat_conf_logging:
      level: info
      to_syslog: false
      to_files: true
      files:
        path: /var/log/metricbeat
        name: metricbeat
        keepfiles: 7
        permissions: 0644

    # Additional modules configuration
    metricbeat_conf_modules_extra:
      - module: apache
        enabled: false
        period: 30s
        hosts: ["http://127.0.0.1"]
        metricsets: ["status"]
      - module: redis
        enabled: false
        period: 10s
        hosts: ["127.0.0.1:6379"]
        metricsets: ["info", "keyspace"]
      - module: mongodb
        enabled: false
        period: 10s
        hosts: ["127.0.0.1:27017"]
        metricsets: ["dbstats", "status"]



  pre_tasks:
    - name: Update package cache (Debian/Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update package cache (RedHat/CentOS)
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install required dependencies
      package:
        name:
          - curl
          - gnupg
        state: present

    - name: Create SSL certificate directory
      file:
        path: /etc/elasticsearch/certs
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: elasticsearch_protocol == "https"

    - name: Check if SSL certificate exists
      stat:
        path: "{{ elasticsearch_ssl_certificate_authorities }}"
      register: ssl_cert_stat
      when: elasticsearch_protocol == "https"

    - name: Warning about SSL certificate
      debug:
        msg: "Warning: SSL certificate not found at {{ elasticsearch_ssl_certificate_authorities }}. Please ensure the certificate is available."
      when: 
        - elasticsearch_protocol == "https"
        - not ssl_cert_stat.stat.exists

  tasks:
    - name: Configure Elastic Repository
      block:
        - name: Add Elastic repository GPG key (Debian/Ubuntu)
          apt_key:
            url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
            state: present
          when: ansible_os_family == "Debian"

        - name: Add Elastic repository (Debian/Ubuntu)
          apt_repository:
            repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
            state: present
            update_cache: yes
          when: ansible_os_family == "Debian"

        - name: Add Elastic repository (RedHat/CentOS)
          yum_repository:
            name: elastic-8.x
            description: Elastic 8.x repository
            baseurl: https://artifacts.elastic.co/packages/8.x/yum
            gpgcheck: yes
            gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
            enabled: yes
          when: ansible_os_family == "RedHat"

    - name: Install metricbeat package
      package:
        name: metricbeat
        state: "{{ metricbeat_package_state }}"

    - name: Create metricbeat main configuration
      copy:
        content: |
          # Ansible managed - Metricbeat Configuration
          
          metricbeat.config.modules:
            path: /etc/metricbeat/modules.d/*.yml
            reload.enabled: false
          
          output.elasticsearch:
            hosts: {{ elasticsearch_hosts | to_json }}
            protocol: "{{ elasticsearch_protocol }}"
            username: "{{ elasticsearch_username }}"
            password: "{{ elasticsearch_password }}"
            preset: balanced
            {% if elasticsearch_protocol == "https" and elasticsearch_ssl_certificate_authorities is defined %}
            ssl:
              certificate_authorities: "{{ elasticsearch_ssl_certificate_authorities }}"
            {% endif %}
          
          setup.template:
            enabled: {{ metricbeat_conf_template_enabled | lower }}
            settings:
              index.number_of_shards: 1
              index.codec: best_compression
          
          processors:
            - add_host_metadata: ~
            - add_cloud_metadata: ~
            - add_docker_metadata: ~
            - add_kubernetes_metadata: ~
          
          tags: ["{{ environment }}", "metricbeat"]
          fields:
            env: "{{ environment }}"
            datacenter: "{{ datacenter }}"
          fields_under_root: false
          
          logging:
            level: {{ metricbeat_log_level | default('info') }}
            to_files: true
            files:
              path: /var/log/metricbeat
              name: metricbeat
              keepfiles: 7
              permissions: 0644
          
          queue.mem:
            events: 4096
            flush.min_events: 512
            flush.timeout: 5s
        dest: /etc/metricbeat/metricbeat.yml
        owner: root
        group: root
        mode: '0600'
        backup: yes
      notify: restart metricbeat

    - name: Collect package facts for auto-detection
      package_facts:
        manager: auto

    - name: Check if Docker is installed
      set_fact:
        docker_installed: "{{ ['docker', 'docker-ce', 'docker.io', 'docker-engine'] | intersect(ansible_facts.packages.keys() | list) | length > 0 }}"

    - name: Check if Nginx is installed
      set_fact:
        nginx_installed: "{{ 'nginx' in ansible_facts.packages }}"

    - name: Check if PostgreSQL is installed
      set_fact:
        postgresql_installed: "{{ 'postgresql-server' in ansible_facts.packages or 'postgresql' in ansible_facts.packages }}"

    - name: Configure System module
      copy:
        content: |
          ---
          - module: system
            metricsets: {{ metricbeat_conf_system_metricsets | to_json }}
            enabled: {{ metricbeat_conf_system_enabled | lower }}
            period: 10s
            processes: ['.*']
            process.include_top_n:
              by_cpu: 5
              by_memory: 5
            cpu.metrics: ["percentages", "normalized_percentages"]
        dest: /etc/metricbeat/modules.d/system.yml
        owner: root
        group: root
        mode: '0644'
      notify: restart metricbeat

    - name: Configure Docker module
      copy:
        content: |
          ---
          - module: docker
            metricsets:
              - container
              - cpu
              - diskio
              - healthcheck
              - info
              - image
              - memory
              - network
            hosts: ["unix:///var/run/docker.sock"]
            period: "{{ metricbeat_conf_docker_period }}"
            enabled: {{ docker_installed | lower }}
        dest: /etc/metricbeat/modules.d/docker.yml
        owner: root
        group: root
        mode: '0644'
      notify: restart metricbeat

    - name: Configure Nginx module
      copy:
        content: |
          ---
          - module: nginx
            metricsets:
              - stubstatus
            hosts: {{ metricbeat_conf_nginx_hosts | to_json }}
            period: "{{ metricbeat_conf_nginx_period }}"
            enabled: {{ nginx_installed | lower }}
            server_status_path: "{{ metricbeat_conf_nginx_status_path }}"
        dest: /etc/metricbeat/modules.d/nginx.yml
        owner: root
        group: root
        mode: '0644'
      notify: restart metricbeat

    - name: Configure PostgreSQL module
      copy:
        content: |
          ---
          - module: postgresql
            metricsets:
              - database
              - bgwriter
              - activity
            hosts: {{ metricbeat_conf_postgresql_hosts | to_json }}
            period: "{{ metricbeat_conf_postgresql_period }}"
            enabled: {{ postgresql_installed | lower }}
            {% if metricbeat_conf_postgresql_user is defined and metricbeat_conf_postgresql_pass is defined %}
            user: "{{ metricbeat_conf_postgresql_user }}"
            password: "{{ metricbeat_conf_postgresql_pass }}"
            {% endif %}
        dest: /etc/metricbeat/modules.d/postgresql.yml
        owner: root
        group: root
        mode: '0644'
      notify: restart metricbeat

    - name: Configure additional modules
      copy:
        content: |
          ---
          {{ metricbeat_conf_modules_extra | to_nice_yaml }}
        dest: /etc/metricbeat/modules.d/additional.yml
        owner: root
        group: root
        mode: '0644'
      notify: restart metricbeat
      when: metricbeat_conf_modules_extra | length > 0

    - name: Enable and start metricbeat service
      systemd:
        name: metricbeat
        state: "{{ metricbeat_service_status }}"
        enabled: "{{ metricbeat_service_enabled }}"
        daemon_reload: yes

  handlers:
    - name: restart metricbeat
      systemd:
        name: metricbeat
        state: restarted
        daemon_reload: yes

  post_tasks:
    - name: Ensure log directory exists
      file:
        path: /var/log/metricbeat
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Wait for metricbeat service to be ready
      wait_for:
        timeout: 30
      delegate_to: localhost

    - name: Test metricbeat configuration
      command: metricbeat test config
      register: config_test
      failed_when: config_test.rc != 0
      changed_when: false

    - name: Test metricbeat output connection
      command: metricbeat test output
      register: output_test
      failed_when: false
      changed_when: false

    - name: Get metricbeat service status
      systemd:
        name: metricbeat
      register: service_status

    - name: Display deployment results
      debug:
        msg:
          - "=== Metricbeat Deployment Results ==="
          - "Configuration Test: {{ 'PASSED' if config_test.rc == 0 else 'FAILED' }}"
          - "Output Connection Test: {{ 'PASSED' if output_test.rc == 0 else 'FAILED - Check Elasticsearch connection' }}"
          - "Service Status: {{ 'RUNNING' if service_status.status.ActiveState == 'active' else 'NOT RUNNING' }}"
          - "Elasticsearch Hosts: {{ elasticsearch_hosts | join(', ') }}"
          - "Protocol: {{ elasticsearch_protocol }}"

    - name: Setup Elasticsearch index template
      command: >
        metricbeat setup --index-management 
        -E output.logstash.enabled=false 
        -E 'output.elasticsearch.hosts={{ elasticsearch_hosts | to_json }}'
        -E 'output.elasticsearch.protocol={{ elasticsearch_protocol }}'
        -E 'output.elasticsearch.username={{ elasticsearch_username }}'
        -E 'output.elasticsearch.password={{ elasticsearch_password }}'
      when: 
        - metricbeat_conf_template_enabled
        - config_test.rc == 0
      run_once: true
      ignore_errors: yes

    - name: Display final status
      debug:
        msg: |
          Metricbeat installation completed!
          
          Next steps:
          1. Verify logs: tail -f /var/log/metricbeat/metricbeat
          2. Check service: systemctl status metricbeat
          3. Monitor metrics in Elasticsearch: {{ elasticsearch_hosts | join(', ') }}
