---
- name: Configure RabbitMQ Master
  hosts: rabbitmq01
  become: yes
  vars:
    rabbitmq_erlang_cookie: "797958d9a756907baad83e25d127c841778b8ad391a9b12720910cbdb134594b"
    rabbitmq_user: "user"
    rabbitmq_password: "kd:Jl.ES0Ui+"
  tasks:
    - name: Ensure RabbitMQ server is running
      command: /opt/bitnami/rabbitmq/sbin/rabbitmq-server -detached
      args:
        creates: /opt/bitnami/rabbitmq/var/lib/rabbitmq/mnesia

    - name: Add Erlang cookie
      copy:
        dest: /opt/bitnami/rabbitmq/.erlang.cookie
        content: "{{ rabbitmq_erlang_cookie }}"
        owner: rabbitmq
        group: rabbitmq
        mode: '0400'

    - name: Enable RabbitMQ management plugin
      command: /opt/bitnami/rabbitmq/sbin/rabbitmq-plugins enable rabbitmq_management
      args:
        creates: /opt/bitnami/rabbitmq/var/lib/rabbitmq/plugins/rabbitmq_management.ez

    - name: Create user for clustering
      command: /opt/bitnami/rabbitmq/sbin/rabbitmqctl add_user {{ rabbitmq_user }} {{ rabbitmq_password }}
      args:
        creates: /opt/bitnami/rabbitmq/var/lib/rabbitmq/mnesia

    - name: Set user tags and permissions
      command: >
        /opt/bitnami/rabbitmq/sbin/rabbitmqctl set_user_tags {{ rabbitmq_user }} administrator &&
        /opt/bitnami/rabbitmq/sbin/rabbitmqctl set_permissions -p / {{ rabbitmq_user }} ".*" ".*" ".*"

- name: Join RabbitMQ Cluster
  hosts: rabbitmq02
  become: yes
  vars:
    rabbitmq_erlang_cookie: "797958d9a756907baad83e25d127c841778b8ad391a9b12720910cbdb134594b"
  tasks:
    - name: Ensure RabbitMQ server is running
      command: /opt/bitnami/rabbitmq/sbin/rabbitmq-server -detached
      args:
        creates: /opt/bitnami/rabbitmq/var/lib/rabbitmq/mnesia

    - name: Add Erlang cookie
      copy:
        dest: /opt/bitnami/rabbitmq/.erlang.cookie
        content: "{{ rabbitmq_erlang_cookie }}"
        owner: rabbitmq
        group: rabbitmq
        mode: '0400'

    - name: Stop RabbitMQ app
      command: /opt/bitnami/rabbitmq/sbin/rabbitmqctl stop_app

    - name: Join RabbitMQ cluster
      command: /opt/bitnami/rabbitmq/sbin/rabbitmqctl join_cluster rabbit@rabbitmq01

    - name: Start RabbitMQ app
      command: /opt/bitnami/rabbitmq/sbin/rabbitmqctl start_app
