---
- name: Add or update user password
  hosts: all
  tasks:
  - name: Change “george” password
    user:
      name: george # user change password
      update_password: always
      password: "{{ newpassword|password_hash('sha512’) }}”
