---
galaxy_info:
  author: your_name
  description: Ansible role to configure RabbitMQ cluster using Bitnami RabbitMQ VMs
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - 12

dependencies: []
