---
# Configure RabbitMQ for cluster
- name: backup old erlang cookie
 # shell: cp -a /var/lib/rabbitmq/.erlang.cookie /var/lib/rabbitmq/.erlang.cookie.old
  shell: cp -a /opt/bitnami/rabbitmq/.rabbitmq/.erlang.cookie /opt/bitnami/rabbitmq/.rabbitmq/.erlang.cookie.old
  changed_when: false

- name: updating rabbitmq erlang cookie
  template:
    src: erlang.cookie.j2
    dest: /opt/bitnami/rabbitmq/.rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
  notify:
    stop rabbitmq-server

- meta: flush_handlers

- name: remove old erlang cookie
  file:
    path: /opt/bitnami/rabbitmq/.rabbitmq/.erlang.cookie.old
    state: absent
  changed_when: false
