---
- name: Enable RabbitMQ management plugin
  command: sudo rabbitmq-plugins enable rabbitmq_management

- name: Set RabbitMQ hostname
  command: hostnamectl set-hostname "{{ inventory_hostname }}"

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items: "{{ hosts_entries }}"

- name: Copy security hardening script
  copy:
    src: security_debian_hardening.sh
    dest: /tmp/security_debian_hardening.sh
    mode: '0755'

- name: Execute security hardening script
  command: /tmp/security_debian_hardening.sh

- name: Stop RabbitMQ app
  command: sudo rabbitmqctl stop_app
  ignore_errors: yes

- name: Reset RabbitMQ
  command: sudo rabbitmqctl reset
  ignore_errors: yes

- name: Join RabbitMQ cluster
  command: sudo rabbitmqctl join_cluster rabbit@rabbitmq1
  when: inventory_hostname != "rabbitmq1"

- name: Start RabbitMQ app
  command: sudo rabbitmqctl start_app
